读

+ read_csv
+ read_excel
+ read_hdf
+ read_sql
+ read_json
+ read_msgpack (experimental)
+ read_html
+ read_gbq (experimental)
+ read_stata
+ read_sas
+ read_clipboard
+ read_pickle

写

+ to_csv
+ to_excel
+ to_hdf
+ to_sql
+ to_json
+ to_msgpack (experimental)
+ to_html
+ to_gbq (experimental)
+ to_stata
+ to_clipboard
+ to_pickle

其它数据源：

+ 数据库
+ 读取网页数据,网络文件
+ 读取股票数据
+ yahoo，世界银行等等

In [1]:
import numpy as np
import pandas as pd

### csv, txt

In [11]:
eu12=pd.read_csv('../data/Eueo2012.csv')
eu12.head()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19

In [43]:
columns=eu12.columns

In [44]:
columns

Index(['Goals', 'Shots on target', 'Shots off target', 'Shooting Accuracy',
       '% Goals-to-shots', 'Total shots (inc. Blocked)', 'Hit Woodwork',
       'Penalty goals', 'Penalties not scored', 'Headed goals', 'Passes',
       'Passes completed', 'Passing Accuracy', 'Touches', 'Crosses',
       'Dribbles', 'Corners Taken', 'Tackles', 'Clearances', 'Interceptions',
       'Clearances off line', 'Clean Sheets', 'Blocks', 'Goals conceded',
       'Saves made', 'Saves-to-shots ratio', 'Fouls Won', 'Fouls Conceded',
       'Offsides', 'Yellow Cards', 'Red Cards', 'Subs on', 'Subs off',
       'Players Used'],
      dtype='object')

In [40]:
eu12=pd.read_csv('../data/Eueo2012.csv',index_col=0)
eu12.head()

,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
Team,,,,,,,,,,,,,,,,,,,,,
Croatia,4,13,12,51.9%,16.0%,32,0,0,0,2,...,13,81.3%,41,62,2,9,0,9,9,16
Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
Denmark,4,10,10,50.0%,20.0%,27,1,0,0,3,...,10,66.7%,25,38,8,4,0,7,7,15
England,5,11,18,50.0%,17.2%,40,0,0,0,3,...,22,88.1%,43,45,6,5,0,11,11,16
France,3,22,24,37.9%,6.5%,65,1,0,0,0,...,6,54.6%,36,51,5,6,0,11,11,19

In [41]:
eu12_header=pd.read_csv('../data/Eueo2012_no_header.csv')
eu12_header.head()

,Croatia,4,13,12,51.90%,16.00%,32,0,0.1,0.2,...,13.1,81.30%,41,62,2.1,9,0.4,9.1,9.2,16
0,Czech Republic,4,13,18,41.90%,12.90%,39,0,0,0,...,9,60.10%,53,73,8,7,0,11,11,19
1,Denmark,4,10,10,50.00%,20.00%,27,1,0,0,...,10,66.70%,25,38,8,4,0,7,7,15
2,England,5,11,18,50.00%,17.20%,40,0,0,0,...,22,88.10%,43,45,6,5,0,11,11,16
3,France,3,22,24,37.90%,6.50%,65,1,0,0,...,6,54.60%,36,51,5,6,0,11,11,19
4,Germany,10,32,32,47.80%,15.60%,80,2,1,0,...,10,62.60%,63,49,12,4,0,15,15,17

In [42]:
eu12_header=pd.read_csv('../data/Eueo2012_no_header.csv',header=None)
eu12_header.head()

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,Croatia,4,13,12,51.90%,16.00%,32,0,0,0,...,13,81.30%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.90%,12.90%,39,0,0,0,...,9,60.10%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.00%,20.00%,27,1,0,0,...,10,66.70%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.00%,17.20%,40,0,0,0,...,22,88.10%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.90%,6.50%,65,1,0,0,...,6,54.60%,36,51,5,6,0,11,11,19

In [45]:
eu12_header=pd.read_csv('../data/Eueo2012_no_header.csv',names=columns)
eu12_header.head()

,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
Croatia,4,13,12,51.90%,16.00%,32,0,0,0,2,...,13,81.30%,41,62,2,9,0,9,9,16
Czech Republic,4,13,18,41.90%,12.90%,39,0,0,0,0,...,9,60.10%,53,73,8,7,0,11,11,19
Denmark,4,10,10,50.00%,20.00%,27,1,0,0,3,...,10,66.70%,25,38,8,4,0,7,7,15
England,5,11,18,50.00%,17.20%,40,0,0,0,3,...,22,88.10%,43,45,6,5,0,11,11,16
France,3,22,24,37.90%,6.50%,65,1,0,0,0,...,6,54.60%,36,51,5,6,0,11,11,19

In [9]:
eu12_header=pd.read_csv('../data/Eueo2012_no_header.csv',names=columns,dtype={'Goals':np.float64})
eu12_header.dtypes

Team                           object
Goals                         float64
Shots on target                 int64
Shots off target                int64
Shooting Accuracy              object
% Goals-to-shots               object
Total shots (inc. Blocked)      int64
Hit Woodwork                    int64
Penalty goals                   int64
Penalties not scored            int64
Headed goals                    int64
Passes                          int64
Passes completed                int64
Passing Accuracy               object
Touches                         int64
Crosses                         int64
Dribbles                        int64
Corners Taken                   int64
Tackles                         int64
Clearances                      int64
Interceptions                   int64
Clearances off line           float64
Clean Sheets                    int64
Blocks                          int64
Goals conceded                  int64
Saves made                      int64
Saves-to-shots ratio           object
Fouls Won                       int64
Fouls Conceded                  int64
Offsides                        int64
Yellow Cards                    int64
Red Cards                       int64
Subs on                         int64
Subs off                        int64
Players Used                    int64
dtype: object

In [58]:
eu12=pd.read_csv('../data/Eueo2012.csv',index_col=0,usecols=['Team','Goals','Shots on target'])
eu12.head()

                Goals  Shots on target
Team
Croatia             4               13
Czech Republic      4               13
Denmark             4               10
England             5               11
France              3               22

In [59]:
eu12.to_csv('../data/Eueo2012_save.csv')

In [56]:
eu12.to_csv?

In [8]:
!type ..\data\Eueo2012_save.csv

Team,Goals,Shots on target
Croatia,4,13
Czech Republic,4,13
Denmark,4,10
England,5,11
France,3,22
Germany,10,32
Greece,5,8
Italy,6,34
Netherlands,2,12
Poland,2,15
Portugal,6,22
Republic of Ireland,1,7
Russia,5,9
Spain,12,42
Sweden,5,17
Ukraine,2,7

### 进阶

In [6]:
!type ..\data\Eueo2012_del.txt

Team?Goals?Shots on target
Croatia?4?13
Czech Republic?4?13
Denmark?4?10
England?5?11
France?3?22
Germany?10?32
Greece?5?8
Italy?6?34
Netherlands?2?12
Poland?2?15
Portugal?6?22
Republic of Ireland?1?7
Russia?5?9
Spain?12?42
Sweden?5?17
Ukraine?2?7

In [14]:
eu12=pd.read_table('../data/Eueo2012_del.txt',index_col=0)
eu12.head()

Empty DataFrame
Columns: []
Index: [Croatia?4?13, Czech Republic?4?13, Denmark?4?10, England?5?11, France?3?22]

In [15]:
eu12=pd.read_csv('../data/Eueo2012_del.txt',sep='?',index_col=0) #csv也可以
eu12.head()

                Goals  Shots on target
Team
Croatia             4               13
Czech Republic      4               13
Denmark             4               10
England             5               11
France              3               22

In [17]:
eu12=pd.read_csv('../data/Eueo2012_skip.txt',sep='?',skiprows=[0,1],index_col=0)
eu12

                     Goals  Shots on target
Team
Croatia                4.0             13.0
Czech Republic         4.0             13.0
Denmark                4.0             10.0
England                5.0             11.0
France                 3.0             22.0
Germany               10.0             32.0
Greece                 5.0              8.0
Italy                  6.0             34.0
Netherlands            2.0             12.0
Poland                 2.0             15.0
Portugal               6.0             22.0
Republic of Ireland    1.0              7.0
Russia                 5.0              9.0
Spain                 12.0             42.0
Sweden                 5.0             17.0
Ukraine                2.0              7.0
This is the end.       NaN              NaN

In [18]:
eu12=pd.read_csv('../data/Eueo2012_skip.txt',sep='?',skiprows=[0,1],skip_footer=1,index_col=0,engine='python') #skip footer 需要制定engine 为python
eu12

                     Goals  Shots on target
Team
Croatia                  4               13
Czech Republic           4               13
Denmark                  4               10
England                  5               11
France                   3               22
Germany                 10               32
Greece                   5                8
Italy                    6               34
Netherlands              2               12
Poland                   2               15
Portugal                 6               22
Republic of Ireland      1                7
Russia                   5                9
Spain                   12               42
Sweden                   5               17
Ukraine                  2                7

In [19]:
eu12=pd.read_table('../data/Eueo2012_del.txt',sep='?',nrows=5,index_col=0)
eu12

                Goals  Shots on target
Team
Croatia             4               13
Czech Republic      4               13
Denmark             4               10
England             5               11
France              3               22

In [20]:
eu12=pd.read_csv('../data/Eueo2012_del.txt',header=0,skiprows=5,nrows=5,sep='?',index_col=0,names=['Goals','Shote on target'])
eu12

             Goals  Shote on target
Germany         10               32
Greece           5                8
Italy            6               34
Netherlands      2               12
Poland           2               15

### excel

In [22]:
eu12=pd.read_excel('../data/Eueo2012_excel.xlsx',sheetname='Eueo2011')
eu12.head()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,8,13,12,0.519,0.160,32,0,0,0,...,13,0.813,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,0.419,0.129,39,0,0,0,...,9,0.601,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,0.500,0.200,27,1,0,0,...,10,0.667,25,38,8,4,0,7,7,15
3,England,5,11,18,0.500,0.172,40,0,0,0,...,22,0.881,43,45,6,5,0,11,11,16
4,France,3,22,24,0.379,0.065,65,1,0,0,...,6,0.546,36,51,5,6,0,11,11,19

In [23]:
eu12.to_excel('../data/test.xlsx')

In [24]:
eu12.to_excel('../data/test1.xlsx',sheet_name='eu2012')

In [25]:
from pandas import ExcelWriter

In [26]:
with ExcelWriter("../data/test3.xls") as writer:
    eu12.to_excel(writer, sheet_name='eu12')
    eu12.to_excel(writer, sheet_name='eu11')

### json

In [14]:
!type ..\data\eueo2012.json

{"Team":{"0":"Croatia","1":"Czech Republic","2":"Denmark","3":"England","4":"France","5":"Germany","6":"Greece","7":"Italy","8":"Netherlands","9":"Poland","10":"Portugal","11":"Republic of Ireland","12":"Russia","13":"Spain","14":"Sweden","15":"Ukraine"},"Goals":{"0":4,"1":4,"2":4,"3":5,"4":3,"5":10,"6":5,"7":6,"8":2,"9":2,"10":6,"11":1,"12":5,"13":12,"14":5,"15":2},"Shots on target":{"0":13,"1":13,"2":10,"3":11,"4":22,"5":32,"6":8,"7":34,"8":12,"9":15,"10":22,"11":7,"12":9,"13":42,"14":17,"15":7},"Shots off target":{"0":12,"1":18,"2":10,"3":18,"4":24,"5":32,"6":18,"7":45,"8":36,"9":23,"10":42,"11":12,"12":31,"13":33,"14":19,"15":26},"Shooting Accuracy":{"0":"51.9%","1":"41.9%","2":"50.0%","3":"50.0%","4":"37.9%","5":"47.8%","6":"30.7%","7":"43.0%","8":"25.0%","9":"39.4%","10":"34.3%","11":"36.8%","12":"22.5%","13":"55.9%","14":"47.2%","15":"21.2%"},"% Goals-to-shots":{"0":"16.0%","1":"12.9%","2":"20.0%","3":"17.2%","4":"6.5%","5":"15.6%","6":"19.2%","7":"7.5%","8":"4.1%","9":"5.2%","10":"9.3%","11":"5.2%","12":"12.5%","13":"16.0%","14":"13.8%","15":"6.0%"},"Total shots (inc. Blocked)":{"0":32,"1":39,"2":27,"3":40,"4":65,"5":80,"6":32,"7":110,"8":60,"9":48,"10":82,"11":28,"12":59,"13":100,"14":39,"15":38},"Hit Woodwork":{"0":0,"1":0,"2":1,"3":0,"4":1,"5":2,"6":1,"7":2,"8":2,"9":0,"10":6,"11":0,"12":2,"13":0,"14":3,"15":0},"Penalty goals":{"0":0,"1":0,"2":0,"3":0,"4":0,"5":1,"6":1,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":1,"14":0,"15":0},"Penalties not scored":{"0":0,"1":0,"2":0,"3":0,"4":0,"5":0,"6":1,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":0},"Headed goals":{"0":2,"1":0,"2":3,"3":3,"4":0,"5":2,"6":0,"7":2,"8":0,"9":1,"10":2,"11":1,"12":1,"13":2,"14":1,"15":2},"Passes":{"0":1076,"1":1565,"2":1298,"3":1488,"4":2066,"5":2774,"6":1187,"7":3016,"8":1556,"9":1059,"10":1891,"11":851,"12":1602,"13":4317,"14":1192,"15":1276},"Passes completed":{"0":828,"1":1223,"2":1082,"3":1200,"4":1803,"5":2427,"6":911,"7":2531,"8":1381,"9":852,"10":1461,"11":606,"12":1345,"13":3820,"14":965,"15":1043},"Passing Accuracy":{"0":"76.9%","1":"78.1%","2":"83.3%","3":"80.6%","4":"87.2%","5":"87.4%","6":"76.7%","7":"83.9%","8":"88.7%","9":"80.4%","10":"77.2%","11":"71.2%","12":"83.9%","13":"88.4%","14":"80.9%","15":"81.7%"},"Touches":{"0":1706,"1":2358,"2":1873,"3":2440,"4":2909,"5":3761,"6":2016,"7":4363,"8":2163,"9":1724,"10":2958,"11":1433,"12":2278,"13":5585,"14":1806,"15":1894},"Crosses":{"0":60,"1":46,"2":43,"3":58,"4":55,"5":101,"6":52,"7":75,"8":50,"9":55,"10":91,"11":43,"12":40,"13":69,"14":44,"15":33},"Dribbles":{"0":42,"1":68,"2":32,"3":60,"4":76,"5":60,"6":53,"7":75,"8":49,"9":39,"10":64,"11":18,"12":40,"13":106,"14":29,"15":26},"Corners Taken":{"0":14,"1":21,"2":16,"3":16,"4":28,"5":35,"6":10,"7":30,"8":22,"9":14,"10":41,"11":8,"12":21,"13":44,"14":7,"15":18},"Tackles":{"0":49,"1":62,"2":40,"3":86,"4":71,"5":91,"6":65,"7":98,"8":34,"9":67,"10":78,"11":45,"12":65,"13":122,"14":56,"15":65},"Clearances":{"0":83,"1":98,"2":61,"3":106,"4":76,"5":73,"6":123,"7":137,"8":41,"9":87,"10":92,"11":78,"12":74,"13":102,"14":54,"15":97},"Interceptions":{"0":56,"1":37,"2":59,"3":72,"4":58,"5":69,"6":87,"7":136,"8":41,"9":62,"10":86,"11":43,"12":58,"13":79,"14":45,"15":29},"Clearances off line":{"0":null,"1":2.0,"2":0.0,"3":1.0,"4":0.0,"5":0.0,"6":0.0,"7":1.0,"8":0.0,"9":0.0,"10":0.0,"11":1.0,"12":0.0,"13":0.0,"14":0.0,"15":0.0},"Clean Sheets":{"0":0,"1":1,"2":1,"3":2,"4":1,"5":1,"6":1,"7":2,"8":0,"9":0,"10":2,"11":0,"12":0,"13":5,"14":1,"15":0},"Blocks":{"0":10,"1":10,"2":10,"3":29,"4":7,"5":11,"6":23,"7":18,"8":9,"9":8,"10":11,"11":23,"12":8,"13":8,"14":12,"15":4},"Goals conceded":{"0":3,"1":6,"2":5,"3":3,"4":5,"5":6,"6":7,"7":7,"8":5,"9":3,"10":4,"11":9,"12":3,"13":1,"14":5,"15":4},"Saves made":{"0":13,"1":9,"2":10,"3":22,"4":6,"5":10,"6":13,"7":20,"8":12,"9":6,"10":10,"11":17,"12":10,"13":15,"14":8,"15":13},"Saves-to-shots ratio":{"0":"81.3%","1":"60.1%","2":"66.7%","3":"88.1%","4":"54.6%","5":"62.6%","6":"65.1%","7":"74.1%","8":"70.6%","9":"66.7%","10":"71.5%","11":"65.4%","12":"77.0%","13":"93.8%","14":"61.6%","15":"76.5%"},"Fouls Won":{"0":41,"1":53,"2":25,"3":43,"4":36,"5":63,"6":67,"7":101,"8":35,"9":48,"10":73,"11":43,"12":34,"13":102,"14":35,"15":48},"Fouls Conceded":{"0":62,"1":73,"2":38,"3":45,"4":51,"5":49,"6":48,"7":89,"8":30,"9":56,"10":90,"11":51,"12":43,"13":83,"14":51,"15":31},"Offsides":{"0":2,"1":8,"2":8,"3":6,"4":5,"5":12,"6":12,"7":16,"8":3,"9":3,"10":10,"11":11,"12":4,"13":19,"14":7,"15":4},"Yellow Cards":{"0":9,"1":7,"2":4,"3":5,"4":6,"5":4,"6":9,"7":16,"8":5,"9":7,"10":12,"11":6,"12":6,"13":11,"14":7,"15":5},"Red Cards":{"0":0,"1":0,"2":0,"3":0,"4":0,"5":0,"6":1,"7":0,"8":0,"9":1,"10":0,"11":1,"12":0,"13":0,"14":0,"15":0},"Subs on":{"0":9,"1":11,"2":7,"3":11,"4":11,"5":15,"6":12,"7":18,"8":7,"9":7,"10":14,"11":10,"12":7,"13":17,"14":9,"15":9},"Subs off":{"0":9,"1":11,"2":7,"3":11,"4":11,"5":15,"6":12,"7":18,"8":7,"9":7,"10":14,"11":10,"12":7,"13":17,"14":9,"15":9},"Players Used":{"0":16,"1":19,"2":15,"3":16,"4":19,"5":17,"6":20,"7":19,"8":15,"9":17,"10":16,"11":17,"12":16,"13":18,"14":18,"15":18}}

In [15]:
eu12_json = pd.read_json("../data/eueo2012.json")
eu12_json.head(5)  #注意这里的顺序发生了改变!如何改回来？比如直接修改column，或者选取列

,% Goals-to-shots,Blocks,Clean Sheets,Clearances,Clearances off line,Corners Taken,Crosses,Dribbles,Fouls Conceded,Fouls Won,...,Shooting Accuracy,Shots off target,Shots on target,Subs off,Subs on,Tackles,Team,Total shots (inc. Blocked),Touches,Yellow Cards
0,16.0%,10,0,83,NaN,14,60,42,62,41,...,51.9%,12,13,9,9,49,Croatia,32,1706,9
1,12.9%,10,1,98,2.0,21,46,68,73,53,...,41.9%,18,13,11,11,62,Czech Republic,39,2358,7
10,9.3%,11,2,92,0.0,41,91,64,90,73,...,34.3%,42,22,14,14,78,Portugal,82,2958,12
11,5.2%,23,0,78,1.0,8,43,18,51,43,...,36.8%,12,7,10,10,45,Republic of Ireland,28,1433,6
12,12.5%,8,0,74,0.0,21,40,40,43,34,...,22.5%,31,9,7,7,65,Russia,59,2278,6

### 数据库


http://sqlitebrowser.org/

In [16]:
import sqlite3
connection = sqlite3.connect("../data/eueo2012.sqlite")
eu12.to_sql("EU12_DATA", connection, if_exists="replace")
#eu12.to_sql("EU12_DATA", connection, if_exists="append")
# commit the SQL and close the connection
connection.commit()
connection.close()

C:\Anaconda\envs\py35\lib\site-packages\pandas\core\generic.py:1165: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  chunksize=chunksize, dtype=dtype)

### hdf5

In [34]:
df = pd.DataFrame(np.random.randn(10, 3),index=pd.date_range('11/11/2016', periods=10),columns=['A', 'B', 'C'])

In [35]:
df

                   A         B         C
2016-11-11 -1.352289 -0.508210 -0.591014
2016-11-12  0.751150 -0.833027  0.445955
2016-11-13 -1.219905  0.209404 -0.124614
2016-11-14  0.027175 -0.850762  1.212795
2016-11-15  0.822153  1.045362  0.974241
2016-11-16 -0.201726  2.870682  0.537832
2016-11-17 -0.503335 -0.834347 -0.007023
2016-11-18 -0.511099 -0.674636  0.032005
2016-11-19  0.050825  0.548531 -0.081896
2016-11-20 -0.745942 -0.108123  1.138219

In [36]:
hdf = pd.HDFStore('../data/hdf.h5')

In [39]:
hdf['df']=df

In [40]:
hdf

<class 'pandas.io.pytables.HDFStore'>
File path: ../data/hdf.h5
/df            frame        (shape->[10,3])

In [41]:
read_hdf = pd.HDFStore("../data/hdf.h5")
df = read_hdf['df']
df

                   A         B         C
2016-11-11 -1.352289 -0.508210 -0.591014
2016-11-12  0.751150 -0.833027  0.445955
2016-11-13 -1.219905  0.209404 -0.124614
2016-11-14  0.027175 -0.850762  1.212795
2016-11-15  0.822153  1.045362  0.974241
2016-11-16 -0.201726  2.870682  0.537832
2016-11-17 -0.503335 -0.834347 -0.007023
2016-11-18 -0.511099 -0.674636  0.032005
2016-11-19  0.050825  0.548531 -0.081896
2016-11-20 -0.745942 -0.108123  1.138219

In [42]:
df.ix[0].A = 1
df

                   A         B         C
2016-11-11  1.000000 -0.508210 -0.591014
2016-11-12  0.751150 -0.833027  0.445955
2016-11-13 -1.219905  0.209404 -0.124614
2016-11-14  0.027175 -0.850762  1.212795
2016-11-15  0.822153  1.045362  0.974241
2016-11-16 -0.201726  2.870682  0.537832
2016-11-17 -0.503335 -0.834347 -0.007023
2016-11-18 -0.511099 -0.674636  0.032005
2016-11-19  0.050825  0.548531 -0.081896
2016-11-20 -0.745942 -0.108123  1.138219

In [43]:
hdf['df']=df

In [44]:
pd.HDFStore("../data/hdf.h5")['df'].head(2)

                  A         B         C
2016-11-11  1.00000 -0.508210 -0.591014
2016-11-12  0.75115 -0.833027  0.445955

### 读取web数据

In [2]:
url='http://worldcup.2014.163.com/playerrank/index.html'

In [3]:
eu2012=pd.read_html(url)  #conda install html5lib ,lxml

In [ ]:
eu2012[0]

In [19]:
df = pd.read_csv("https://github.com/zjdian/data-analysis/blob/master/data/sp500.csv")

CParserError: Error tokenizing data. C error: Expected 1 fields in line 104, saw 3